on:
  push:
    branches:
      - feature/*
      - develop
  workflow_dispatch:

env:
  NODE_VERSION: '14.x'
  APPLICATION_NAME: 'zeeven'
  APPLICATION_TYPE: 'ms'

permissions:
  contents: read

jobs:
  create-folder:
    name: Create folder
    runs-on: ubuntu-latest
    steps:
    - name: Create folder
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_APPLICATIONS_HOST }}
        port: ${{ secrets.PROD_APPLICATIONS_PORT }}
        username: ${{ secrets.PROD_APPLICATIONS_USERNAME }}
        key: ${{ secrets.PROD_APPLICATIONS_SSH_PRIVATE_KEY }}
        script: |
          sudo mkdir -p /opt/applications/zeeven/ms-zeeven
          sudo chmod ugo+rwx /opt/applications/zeeven/ms-zeeven

  copy-configs:
    name: "copy configs"
    runs-on: ubuntu-latest
    needs: create-folder
    steps:
      - uses: actions/checkout@master
      - name: update configs
        run: |
          sed -i 's|IMAGE_NAME|simachille/${{env.APPLICATION_TYPE}}-${{env.APPLICATION_NAME}}:${{ github.sha }}|' docker-compose.yml
          sed -i 's/WHATAPPS_TOKEN/${{ secrets.WHATSAPP_TOKEN }}/g' docker-compose.yml

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_APPLICATIONS_HOST }}
          port: ${{ secrets.PROD_APPLICATIONS_PORT }}
          username: ${{ secrets.PROD_APPLICATIONS_USERNAME }}
          key: ${{ secrets.PROD_APPLICATIONS_SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: '/opt/applications/${{env.APPLICATION_NAME}}/${{env.APPLICATION_TYPE}}-${{env.APPLICATION_NAME}}'
  generate-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update Version
        run: mvn build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} versions:commit
      - name: Check Version
        run: |
          cat pom.xml
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -Dmaven.test.skip=true clean compile package

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: simachille/ms-zeeven

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: simachille/ms-zeeven:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

  run-container:
    name: "Run container"
    runs-on: ubuntu-latest
    needs: [dockerize, copy-configs]
    steps:
    - name: Run container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PROD_APPLICATIONS_HOST }}
        port: ${{ secrets.PROD_APPLICATIONS_PORT }}
        username: ${{ secrets.PROD_APPLICATIONS_USERNAME }}
        key: ${{ secrets.PROD_APPLICATIONS_SSH_PRIVATE_KEY }}
        script: |
          docker compose -f /opt/applications/zeeven/ms-zeeven/docker-compose.yml rm -f
          docker compose -f /opt/applications/zeeven/ms-zeeven/docker-compose.yml stop
          docker rmi -f simachille/ms-zeeven:${{ github.sha }}
          rm -f /opt/applications/zeeven/ms-zeeven/.env
          echo WHATSAPP_TOKEN=${{ secrets.WHATSAPP_TOKEN }} >> /opt/applications/zeeven/ms-zeeven/.env
          echo NOTIFICATIONS_HOST=${{ secrets.NOTIFICATIONS_HOST }} >> /opt/applications/zeeven/ms-zeeven/.env
          echo ZEEVEN_HOST=${{ secrets.ZEEVEN_HOST }} >> /opt/applications/zeeven/ms-zeeven/.env
          echo STRIPE_PUBLIC_KEY=${{ secrets.PROD_STRIPE_PUBLIC_KEY }} >> /opt/applications/zeeven/ms-zeeven/.env
          echo STRIPE_SECRET_KEY=${{ secrets.PROD_STRIPE_SECRET_KEY }} >> /opt/applications/zeeven/ms-zeeven/.env
          echo STRIPE_WEBHOOKSECRET_KEY=${{ secrets.STRIPE_WEBHOOKSECRET_KEY }} >> /opt/applications/zeeven/ms-zeeven/.env
          echo PROD_IPLOCATION_API_KEY=${{ secrets.PROD_IPLOCATION_API_KEY }} >> /opt/applications/zeeven/ms-zeeven/.env
          echo PROD_BACKOFFICE_API_KEY=${{ secrets.PROD_BACKOFFICE_API_KEY }} >> /opt/applications/zeeven/ms-zeeven/.env
          docker compose -f /opt/applications/zeeven/ms-zeeven/docker-compose.yml pull
          docker compose -f /opt/applications/zeeven/ms-zeeven/docker-compose.yml up -d
          rm -f /opt/applications/zeeven/ms-zeeven/.env
